# Dataset and dataloader parameters
dataset: 'commonroad'

batch_size: 96
num_workers: 10


# Encoder parameters
encoder_type: 'pgp_encoder'
encoder_args:
  target_agent_feat_size: 5
  target_agent_emb_size: 16
  target_agent_enc_size: 64
  node_feat_size: 6
  node_emb_size: 16
  node_enc_size: 64
  nbr_feat_size: 5
  nbr_emb_size: 16
  nbr_enc_size: 64
  num_gat_layers: 2

# Aggregator parameters
aggregator_type: 'global_attention'
aggregator_args:
  target_agent_enc_size: 64
  emb_size: 128
  num_heads: 32
  context_enc_size: 64


# Decoder parameters
decoder_type: 'mtp'
decoder_args:
  op_len: 12
  hidden_size: 128
  encoding_size: 192
  use_variance: False # TODO: some bug in relevant loss calculation
  num_modes: 10


# Optimizer parameters
optim_args:
  lr: 0.001
  scheduler_step: 50
  scheduler_gamma: 0.5


losses: ['min_ade_k', 'miss_rate_k', 'mtp_loss']
loss_weights: [1.0, 1.0, 0.5]
loss_args:
  - k: 10
  - k: 10
    dist_thresh: 2
  - dummy: 0

tr_metrics: ['min_ade_k', 'min_ade_k','miss_rate_k', 'mtp_loss']
tr_metric_args:
  - k: 5
  - k: 10
  - k: 10
    dist_thresh: 2
  - dummy: 0

val_metrics: ['min_ade_k','min_ade_k', 'miss_rate_k', 'miss_rate_k', 'mtp_loss']
val_metric_args:
  - k: 5
  - k: 10
  - k: 5
    dist_thresh: 2
  - k: 10
    dist_thresh: 2
  - dummy: 0


log_freq: 100
