# Dataset and dataloader parameters
dataset: 'commonroad'

batch_size: 96
num_workers: 10

# Encoder parameters
encoder_type: 'pgp_encoder'
encoder_args:
  target_agent_feat_size: 5
  target_agent_emb_size: 16
  target_agent_enc_size: 32
  node_feat_size: 6
  node_emb_size: 16
  node_enc_size: 32
  nbr_feat_size: 5
  nbr_emb_size: 16
  nbr_enc_size: 32
  num_gat_layers: 2

# Aggregator parameters
aggregator_type: 'pgp'
aggregator_args:
  pre_train: False
  target_agent_enc_size: 32
  node_enc_size: 32
  pi_h1_size: 32
  pi_h2_size: 32
  horizon: 15
  num_samples: 500 # 1000
  emb_size: 128
  num_heads: 32


# Decoder parameters
decoder_type: 'lvm'
decoder_args:
  num_samples: 500 # 1000
  op_len: 12
  hidden_size: 128
  encoding_size: 160
  agg_type: 'sample_specific'
  lv_dim: 5
  num_clusters: 10


# Optimizer parameters
# recommend: 250
optim_args:
  lr: 0.002
  scheduler_step: 50
  scheduler_gamma: 0.6


losses: ['min_ade_k', 'min_ade_k', 'miss_rate_k', 'miss_rate_k', 'pi_bc']
loss_weights: [1.0, 1.0, 1.0, 1.0, 0.5]
loss_args:
  - k: 5
  - k: 10
  - k: 5
    dist_thresh: 2
  - k: 10
    dist_thresh: 2
  - dummy: 0


tr_metrics: ['min_ade_k', 'miss_rate_k', 'pi_bc']
tr_metric_args:
  - k: 10
  - k: 10
    dist_thresh: 2
  - dummy: 0

val_metrics: ['min_ade_k','min_ade_k', 'miss_rate_k', 'miss_rate_k', 'pi_bc']
val_metric_args:
  - k: 5
  - k: 10
  - k: 5
    dist_thresh: 2
  - k: 10
    dist_thresh: 2
  - dummy: 0


log_freq: 100
